// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVMkZ0LjJ6HQ251hVA4rQzRGZR7SkkNXo',
    appId: '1:832571020314:web:49149c38118139b44aeda3',
    messagingSenderId: '832571020314',
    projectId: 'surat-e30f7',
    authDomain: 'surat-e30f7.firebaseapp.com',
    storageBucket: 'surat-e30f7.appspot.com',
    measurementId: 'G-QJVV28XR1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9WwQpPiX8tKt3xOXjsWP5Kz-hhsvd3L8',
    appId: '1:832571020314:android:6ca102ba7d35c7cc4aeda3',
    messagingSenderId: '832571020314',
    projectId: 'surat-e30f7',
    storageBucket: 'surat-e30f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtPeC0p6gBRYnNKo0Or5z73Yv8j4gVW_s',
    appId: '1:832571020314:ios:86a4b4e75c2b708f4aeda3',
    messagingSenderId: '832571020314',
    projectId: 'surat-e30f7',
    storageBucket: 'surat-e30f7.appspot.com',
    androidClientId: '832571020314-f63rafro4f03afq10e3m3246s8qac5eh.apps.googleusercontent.com',
    iosClientId: '832571020314-br36nfjs5kemf5jrcrgfa5re5oprbdhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttercuredoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtPeC0p6gBRYnNKo0Or5z73Yv8j4gVW_s',
    appId: '1:832571020314:ios:ec010f7636d177004aeda3',
    messagingSenderId: '832571020314',
    projectId: 'surat-e30f7',
    storageBucket: 'surat-e30f7.appspot.com',
    androidClientId: '832571020314-f63rafro4f03afq10e3m3246s8qac5eh.apps.googleusercontent.com',
    iosClientId: '832571020314-03pdlr4l7pserla3g05qhcs2vkk91v2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttercuredoc.RunnerTests',
  );
}
