// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzmsFmPrB2CzgCtwJqCf2iYyHwD2iqrb4',
    appId: '1:202759056429:web:45db3c5584647ede6ddca4',
    messagingSenderId: '202759056429',
    projectId: 'cures-9495f',
    authDomain: 'cures-9495f.firebaseapp.com',
    storageBucket: 'cures-9495f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYD7Yo74DwR2ApPGB6BGu95Tw7OYjKY5o',
    appId: '1:202759056429:android:7de770554c5f8cd46ddca4',
    messagingSenderId: '202759056429',
    projectId: 'cures-9495f',
    storageBucket: 'cures-9495f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWj4BGI40zwWguK5-6fpormLdXEAWrgDU',
    appId: '1:202759056429:ios:598ff59c4a2a0f106ddca4',
    messagingSenderId: '202759056429',
    projectId: 'cures-9495f',
    storageBucket: 'cures-9495f.appspot.com',
    androidClientId: '202759056429-utjm7uaj3ka8ra1nl1fft9714rsgt8g7.apps.googleusercontent.com',
    iosClientId: '202759056429-v4aasc4vnetb35bmdtodk45tigemt53v.apps.googleusercontent.com',
    iosBundleId: 'com.example.tpop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWj4BGI40zwWguK5-6fpormLdXEAWrgDU',
    appId: '1:202759056429:ios:b4a15108266c19de6ddca4',
    messagingSenderId: '202759056429',
    projectId: 'cures-9495f',
    storageBucket: 'cures-9495f.appspot.com',
    androidClientId: '202759056429-utjm7uaj3ka8ra1nl1fft9714rsgt8g7.apps.googleusercontent.com',
    iosClientId: '202759056429-svlq8ouh5b7i3ih1garbrjke9jntdq1f.apps.googleusercontent.com',
    iosBundleId: 'com.example.tpop.RunnerTests',
  );
}
